[package]
name = "iso-network-manager"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures = "0.3.32"
ipnetwork = "0.21.1"
iso-common = { path = "../iso-common" }
libc = "0.2.186"
netns-rs = "0.2.0"
rtnetlink = "0.21.0"
rustables = "0.8.7"
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "macros", "net", "io-util"] }
