#!/usr/bin/env bash
# Regenerate the admin API document from the daemon's code and the Rust client
# crate from that document.
#
#   crates/iso-client/openapi.json     <- iso-openapi (utoipa annotations in iso-controld)
#   crates/iso-client/src/generated.rs <- cargo progenitor (https://github.com/oxidecomputer/progenitor)
#
# Needs `cargo install cargo-progenitor`. A test in iso-controld fails when
# openapi.json is stale, so run this after changing any admin handler or DTO.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

cargo run -q -p iso-controld --bin iso-openapi > crates/iso-client/openapi.json
echo "wrote crates/iso-client/openapi.json"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
cargo progenitor -i crates/iso-client/openapi.json -o "$tmp/iso-client" \
  -n iso-client -v 0.1.0 --license-name MIT --interface builder >/dev/null
{
  echo '// GENERATED by scripts/gen-client.sh from crates/iso-client/openapi.json (cargo-progenitor). Do not edit.'
  echo '#![allow(clippy::all, unused_imports, dead_code)]'
  cat "$tmp/iso-client/src/lib.rs"
} > crates/iso-client/src/generated.rs
echo "wrote crates/iso-client/src/generated.rs ($(wc -l < crates/iso-client/src/generated.rs) lines)"
echo "progenitor wanted these dependencies; keep crates/iso-client/Cargo.toml in step:"
sed -n '/^\[dependencies\]/,$p' "$tmp/iso-client/Cargo.toml"
